import type { FC } from "react";
import { useEffect } from "react";
import { useNavigate } from "react-router-dom";
import { useChat } from "../hooks/useChat";
import EmptyState from "../components/common/EmptyState";

/** Lists finalized (STATUS: READY) requirements gathered across all RTE conversations. */
const RequirementsPage: FC = () => {
  const { conversations, refreshConversationList } = useChat();
  const navigate = useNavigate();

  useEffect(() => {
    refreshConversationList();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const finalized = conversations.filter((c) => c.hasFinalStory);

  return (
    <div style={{ maxWidth: 760, margin: "0 auto", padding: 24 }}>
      <h2 style={{ marginBottom: 4 }}>Requirements</h2>
      <p style={{ color: "#5b6270", marginTop: 0 }}>
        Finalized user stories generated by the RTE agent. Select one to reopen the full conversation.
      </p>

      {finalized.length === 0 ? (
        <EmptyState
          title="No finalized requirements yet"
          description="Submit a business requirement on the RTE page and answer any clarifying questions to see it here."
        />
      ) : (
        <div style={{ display: "flex", flexDirection: "column", gap: 8 }}>
          {finalized.map((conversation) => (
            <button
              type="button"
              key={conversation.id}
              onClick={() => navigate(`/rte?c=${conversation.id}`)}
              className="korame-card"
              style={{
                textAlign: "left",
                padding: "12px 14px",
                borderRadius: 8,
                border: "1px solid #e2e5eb",
                background: "#fff",
                cursor: "pointer",
              }}
            >
              <div style={{ fontWeight: 600 }}>
                {conversation.storyTitle || conversation.preview || "Untitled requirement"}
              </div>
              {conversation.storyTitle && conversation.preview && (
                <div style={{ fontSize: 12, color: "#5b6270", marginTop: 2 }}>
                  Originally asked: {conversation.preview}
                </div>
              )}
              <div style={{ fontSize: 12, color: "#5b6270", marginTop: 2 }}>
                {new Date(conversation.updatedAt).toLocaleString()}
              </div>
            </button>
          ))}
        </div>
      )}
    </div>
  );
};

export default RequirementsPage;
